### ISSUE TITLE
Introduce a mechanism for overriding directives

### ISSUE THREAD

**Issue by bryanmtl** [DynamoMTL/sprangular#60]

**Comment by bryanmtl** [comment]
cc: @LaurentDario

**Comment by joshnuss** [comment]
@bryanmtl just tested it out. The trick is to set `priority` on the overwritten version of the directive.

For example say we have a directive "<awesome-directive/>", it can be overwritten by creating a directive with the same name in the host app's module, and setting priority to a higher number

```coffeescript
angular.module('Sprangular', [])
  .directive 'awesomeDirective', ->
    restrict: 'E'
    template: '<h1>Sprangular Version</h1>'
        
angular.module('MyApp', ['Sprangular'])    
  .directive 'awesomeDirective', ->
    restrict: 'E'
    priority: 100
    template: '<h1>MyApp Version</h1>'
```

**Comment by bryanmtl** [comment]
Cool, thanks @joshnuss
